@echo off
echo Deteniendo procesos de Node.js...
taskkill /F /IM node.exe 2>nul

echo Esperando 3 segundos...
timeout /t 3 /nobreak >nul

echo Limpiando cache de Next.js...
if exist .next rmdir /s /q .next

echo Iniciando servidor de desarrollo...
npm run dev
