// Plantillas predefinidas de Hero para diferentes categorías de eventos

export const HERO_TEMPLATES = {
  boda: {
    category: 'Boda',
    icon: 'Heart',
    templates: [
      {
        id: 'boda-1',
        name: 'Elegante Clásico',
        thumbnail: 'GiDiamondRing',
        props: {
          title: 'Ana & Carlos',
          subtitle: 'NOS CASAMOS',
          backgroundImage: '',
          backgroundColor: '#f8f4f0',
          textAlign: 'center',
          textColor: '#2c3e50',
          paddingY: '120px',
        },
      },
      {
        id: 'boda-2',
        name: 'Romántico Floral',
        thumbnail: 'GiFlowerEmblem',
        props: {
          title: 'María & Juan',
          subtitle: 'CELEBRA CON NOSOTROS',
          backgroundImage: '',
          backgroundColor: '#fff0f5',
          textAlign: 'center',
          textColor: '#8e44ad',
          paddingY: '140px',
        },
      },
      {
        id: 'boda-3',
        name: 'Moderno Minimalista',
        thumbnail: 'LuSparkles',
        props: {
          title: 'NUESTRA BODA',
          subtitle: 'Laura & Diego | 20.08.2025',
          backgroundImage: '',
          backgroundColor: '#ffffff',
          textAlign: 'center',
          textColor: '#2c3e50',
          paddingY: '160px',
        },
      },
      {
        id: 'boda-4',
        name: 'Vintage Gold',
        thumbnail: 'GiStarShuriken',
        props: {
          title: 'Sofia & Andrés',
          subtitle: 'Save the Date',
          backgroundImage: '',
          backgroundColor: '#fdf5e6',
          textColor: '#b8860b',
          textAlign: 'center',
          paddingY: '130px',
        },
      },
      {
        id: 'boda-5',
        name: 'Noche Estrellada',
        thumbnail: 'GiMoon',
        props: {
          title: 'Valeria & Miguel',
          subtitle: 'Bajo las estrellas',
          backgroundImage: '',
          backgroundColor: '#1a1a2e',
          textColor: '#f1c40f',
          textAlign: 'center',
          paddingY: '150px',
        },
      },
    ],
  },

  quince: {
    category: '15 Años',
    icon: 'Sparkles',
    templates: [
      {
        id: 'quince-1',
        name: 'Rose Gold',
        thumbnail: 'GiQueenCrown',
        props: {
          title: 'MIS XV AÑOS',
          subtitle: 'Isabella',
          backgroundImage: '',
          backgroundColor: '#ffe4e1',
          textAlign: 'center',
          textColor: '#d35400',
          paddingY: '140px',
        },
      },
      {
        id: 'quince-2',
        name: 'Golden Night',
        thumbnail: 'GiStarShuriken',
        props: {
          title: 'XV AÑOS',
          subtitle: 'Camila • 25 de Marzo',
          backgroundImage: '',
          backgroundColor: '#000000',
          textAlign: 'center',
          textColor: '#ffd700',
          paddingY: '150px',
        },
      },
      {
        id: 'quince-3',
        name: 'Blue Dream',
        thumbnail: 'GiButterfly',
        props: {
          title: 'SOFÍA',
          subtitle: 'Mis Dulces 16',
          backgroundImage: '',
          backgroundColor: '#e0ffff',
          textAlign: 'center',
          textColor: '#00ced1',
          paddingY: '130px',
        },
      },
      {
        id: 'quince-4',
        name: 'Silver Star',
        thumbnail: 'GiStarFormation',
        props: {
          title: 'VALENTINA',
          subtitle: 'Festejando mis 15',
          backgroundImage: '',
          backgroundColor: '#f5f5f5',
          textAlign: 'center',
          textColor: '#7f8c8d',
          paddingY: '140px',
        },
      },
      {
        id: 'quince-5',
        name: 'Lavender Fields',
        thumbnail: 'GiFlowerPot',
        props: {
          title: 'Daniela',
          subtitle: 'XV Años',
          backgroundImage: '',
          backgroundColor: '#e6e6fa',
          textAlign: 'center',
          textColor: '#8e44ad',
          paddingY: '120px',
        },
      },
    ],
  },

  cumpleanos: {
    category: 'Cumpleaños Infantiles',
    icon: 'Cake',
    templates: [
      {
        id: 'superman-1',
        name: 'Estilo Hombre de Acero',
        thumbnail: 'GiSupersonicArrow',
        props: {
          title: '¡SÚPER CUMPLEAÑOS!',
          subtitle: 'Te invito a mi fiesta',
          backgroundImage: '',
          backgroundColor: '#00539C',
          textAlign: 'center',
          textColor: '#F2C622',
          paddingY: '120px',
        },
      },
      {
        id: 'batman-1',
        name: 'Estilo Caballero Oscuro',
        thumbnail: 'GiBat',
        props: {
          title: 'BAT-FIESTA',
          subtitle: 'La Bati-señal te llama',
          backgroundImage: '',
          backgroundColor: '#1C1C1C',
          textAlign: 'center',
          textColor: '#F5E050',
          paddingY: '130px',
        },
      },
      {
        id: 'ironman-1',
        name: 'Estilo Vengador Dorado',
        thumbnail: 'GiRobotHelmet',
        props: {
          title: 'FIESTA ÉPICA',
          subtitle: 'Stark Industries presenta...',
          backgroundImage: '',
          backgroundColor: '#7A0000',
          textAlign: 'center',
          textColor: '#F3D188',
          paddingY: '120px',
        },
      },
      {
        id: 'spiderman-1',
        name: 'Estilo Arácnido',
        thumbnail: 'GiSpiderWeb',
        props: {
          title: 'SPIDER-PARTY',
          subtitle: 'Un gran poder conlleva una gran fiesta',
          backgroundImage: '',
          backgroundColor: '#E23636',
          textAlign: 'center',
          textColor: '#FFFFFF',
          paddingY: '120px',
        },
      },
      {
        id: 'princess-1',
        name: 'Reino de Hielo',
        thumbnail: 'GiSnowflake1',
        props: {
          title: 'FIESTA MÁGICA',
          subtitle: 'Una aventura congelada',
          backgroundImage: '',
          backgroundColor: '#A5F2F3',
          textAlign: 'center',
          textColor: '#2E86C1',
          paddingY: '120px',
        },
      },
    ],
  },

  babyshower: {
    category: 'Baby Shower',
    icon: 'Baby',
    templates: [
      {
        id: 'baby-1',
        name: 'Baby Boy',
        thumbnail: 'GiBabyFace',
        props: {
          title: 'ES UN NIÑO',
          subtitle: 'Esperando a Mateo',
          backgroundImage: '',
          backgroundColor: '#e6f7ff',
          textAlign: 'center',
          textColor: '#1890ff',
          paddingY: '110px',
        },
      },
      {
        id: 'baby-2',
        name: 'Baby Girl',
        thumbnail: 'GiHeartRibbon',
        props: {
          title: 'ES UNA NIÑA',
          subtitle: 'Bienvenida Emma',
          backgroundImage: '',
          backgroundColor: '#fff0f6',
          textAlign: 'center',
          textColor: '#eb2f96',
          paddingY: '110px',
        },
      },
      {
        id: 'baby-3',
        name: 'Neutral Beige',
        thumbnail: 'GiTeddyBear',
        props: {
          title: 'BABY SHOWER',
          subtitle: 'Bebé en camino',
          backgroundImage: '',
          backgroundColor: '#f5f5dc',
          textAlign: 'center',
          textColor: '#8b4513',
          paddingY: '120px',
        },
      },
      {
        id: 'baby-4',
        name: 'Safari Adventure',
        thumbnail: 'GiLion',
        props: {
          title: 'WILD ONE',
          subtitle: 'Baby Shower de Lucas',
          backgroundImage: '',
          backgroundColor: '#f0fff0',
          textAlign: 'center',
          textColor: '#228b22',
          paddingY: '130px',
        },
      },
      {
        id: 'baby-5',
        name: 'Clouds & Stars',
        thumbnail: 'GiCloudRing',
        props: {
          title: 'DULCE ESPERA',
          subtitle: 'Soñando contigo',
          backgroundImage: '',
          backgroundColor: '#f0f8ff',
          textAlign: 'center',
          textColor: '#708090',
          paddingY: '110px',
        },
      },
    ],
  },

  graduacion: {
    category: 'Graduación',
    icon: 'GraduationCap',
    templates: [
      {
        id: 'grad-1',
        name: 'Classic Blue',
        thumbnail: 'GiGraduateCap',
        props: {
          title: 'GRADUACIÓN 2025',
          subtitle: 'Clase del 2025',
          backgroundImage: '',
          backgroundColor: '#002147',
          textAlign: 'center',
          textColor: '#ffffff',
          paddingY: '140px',
        },
      },
      {
        id: 'grad-2',
        name: 'Elegant Black',
        thumbnail: 'GiTrophy',
        props: {
          title: 'LO LOGRAMOS',
          subtitle: 'Generación de Excelencia',
          backgroundImage: '',
          backgroundColor: '#111111',
          textAlign: 'center',
          textColor: '#d4af37',
          paddingY: '140px',
        },
      },
      {
        id: 'grad-3',
        name: 'Modern White',
        thumbnail: 'GiScrollUnfurled',
        props: {
          title: 'FELICIDADES',
          subtitle: 'Ingeniera Andrea Martínez',
          backgroundImage: '',
          backgroundColor: '#ffffff',
          textAlign: 'center',
          textColor: '#333333',
          paddingY: '120px',
        },
      },
      {
        id: 'grad-4',
        name: 'Success Green',
        thumbnail: 'GiOakLeaf',
        props: {
          title: 'NUEVOS COMIENZOS',
          subtitle: 'El futuro es nuestro',
          backgroundImage: '',
          backgroundColor: '#e8f5e9',
          textAlign: 'center',
          textColor: '#1b5e20',
          paddingY: '130px',
        },
      },
      {
        id: 'grad-5',
        name: 'University Red',
        thumbnail: 'GiMedal',
        props: {
          title: 'GRADUADO',
          subtitle: 'Lic. en Derecho',
          backgroundImage: '',
          backgroundColor: '#800000',
          textAlign: 'center',
          textColor: '#ffffff',
          paddingY: '140px',
        },
      },
    ],
  },

  corporativo: {
    category: 'Corporativo',
    icon: 'Briefcase',
    templates: [
      {
        id: 'corp-1',
        name: 'Corporate Blue',
        thumbnail: 'GiModernCity',
        props: {
          title: 'CONFERENCIA ANUAL',
          subtitle: 'Innovando el Futuro',
          backgroundImage: '',
          backgroundColor: '#2c3e50',
          textAlign: 'center',
          textColor: '#ecf0f1',
          paddingY: '150px',
        },
      },
      {
        id: 'corp-2',
        name: 'Tech Dark',
        thumbnail: 'GiComputerFan',
        props: {
          title: 'TECH SUMMIT 2025',
          subtitle: 'Conectando Mentes',
          backgroundImage: '',
          backgroundColor: '#000000',
          textAlign: 'center',
          textColor: '#00ff00',
          paddingY: '140px',
        },
      },
      {
        id: 'corp-3',
        name: 'Product Launch',
        thumbnail: 'GiRocketFlight',
        props: {
          title: 'LANZAMIENTO',
          subtitle: 'Descubre la nueva era',
          backgroundImage: '',
          backgroundColor: '#6c5ce7',
          textAlign: 'center',
          textColor: '#ffffff',
          paddingY: '160px',
        },
      },
      {
        id: 'corp-4',
        name: 'Business Seminar',
        thumbnail: 'GiHistogram',
        props: {
          title: 'ESTRATEGIA 360',
          subtitle: 'Seminario de Negocios',
          backgroundImage: '',
          backgroundColor: '#ecf0f1',
          textAlign: 'center',
          textColor: '#2c3e50',
          paddingY: '120px',
        },
      },
      {
        id: 'corp-5',
        name: 'Gala Night',
        thumbnail: 'GiWineGlass',
        props: {
          title: 'CENA DE GALA',
          subtitle: 'Celebrando el éxito',
          backgroundImage: '',
          backgroundColor: '#2d3436',
          textAlign: 'center',
          textColor: '#fdcb6e',
          paddingY: '150px',
        },
      },
    ],
  },
};

export const getAllHeroTemplates = () => {
  return Object.values(HERO_TEMPLATES);
};

export const getTemplatesByCategory = (category) => {
  return HERO_TEMPLATES[category]?.templates || [];
};
