// Configuración de todos los tipos de secciones disponibles

export const FONT_OPTIONS = ['', 'Roboto', 'Open Sans', 'Lato', 'Montserrat', 'Oswald', 'Raleway', 'Inter', 'Poppins', 'Nunito', 'Playfair Display', 'Merriweather', 'Lora', 'PT Serif', 'Libre Baskerville', 'Cormorant Garamond', 'EB Garamond', 'Cinzel', 'Great Vibes', 'Dancing Script', 'Pacifico', 'Satisfy', 'Caveat', 'Cookie', 'Courgette', 'Allura', 'Alex Brush', 'Parisienne', 'Sacramento', 'Amatic SC', 'Lobster', 'Anton', 'Fjalla One', 'Signika', 'Arvo', 'Varela Round', 'Comfortaa', 'Abril Fatface', 'Josefin Sans', 'Asap', 'Prompt', 'Bebas Neue', 'Righteous', 'Permanent Marker', 'Fredoka One', 'Alfa Slab One', 'Patua One', 'Teko', 'Acme', 'Questrial', 'Cinzel Decorative', 'Pinyon Script', 'Tangerine', 'Italianno', 'Bad Script', 'Petit Formal Script', 'Antic Didone', 'Work Sans'];

/* ── Universal background props injected into every section ── */
const BG_DEFAULTS = {
  bgImage: '',
  bgColor: '',
  bgGradient: '',
  bgType: 'none',   // 'none' | 'color' | 'gradient' | 'image'
  bgOpacity: 100,
};

const BG_FIELDS = [
  { name: '_bg_separator', label: 'Fondo del bloque', type: 'separator' },
  { name: 'bgType', label: 'Tipo de fondo', type: 'select', options: ['none', 'color', 'gradient', 'image'] },
  { name: 'bgColor', label: 'Color de fondo', type: 'color', showWhen: { field: 'bgType', value: 'color' } },
  { name: 'bgGradient', label: 'Gradiente (CSS)', type: 'text', placeholder: 'linear-gradient(135deg, #ff6b6b, #5f27cd)', showWhen: { field: 'bgType', value: 'gradient' } },
  { name: 'bgImage', label: 'Imagen de fondo', type: 'image', showWhen: { field: 'bgType', value: 'image' } },
  { name: 'bgOpacity', label: 'Opacidad del fondo (%)', type: 'range', min: 0, max: 100 },
];

export const SECTION_TYPES = {
  hero: {
    id: 'hero',
    label: 'Hero',
    icon: 'Layout',
    description: 'Sección principal con título y fondo',
    defaultProps: {
      title: 'Nuestra Boda',
      subtitle: '25 de Diciembre, 2025',
      showTitle: true,
      showSubtitle: true,
      backgroundImage: '',
      backgroundImagePos: '50% 50%',
      backgroundImageFilter: '',
      textAlign: 'center',
      textColor: '#1a1a1a',
      paddingY: '80px',
      overlayOpacity: 0,
    },
    fields: [
      { name: 'showTitle', label: 'Mostrar título', type: 'checkbox' },
      { name: 'title', label: 'Título', type: 'text' },
      { name: 'showSubtitle', label: 'Mostrar subtítulo', type: 'checkbox' },
      { name: 'subtitle', label: 'Subtítulo', type: 'text' },
      { name: 'backgroundImage', label: 'Imagen de fondo', type: 'image-editable' },
      { name: 'overlayOpacity', label: 'Oscurecimiento del fondo (%)', type: 'range', min: 0, max: 80 },
      { name: 'textAlign', label: 'Alineación', type: 'select', options: ['left', 'center', 'right'] },
      { name: 'textColor', label: 'Color de texto', type: 'color' },
      { name: 'titleFont', label: 'Fuente del Título', type: 'font', options: FONT_OPTIONS },
      { name: 'textFont', label: 'Fuente del Texto', type: 'font', options: FONT_OPTIONS },
      { name: 'paddingY', label: 'Espaciado vertical (px)', type: 'number-unit', defaultUnit: 'px', units: ['px'] },
    ],
  },
  
  text: {
    id: 'text',
    label: 'Texto',
    icon: 'Type',
    description: 'Bloque de texto enriquecido',
    defaultProps: {
      content: 'Escribe tu texto aquí...',
      textAlign: 'left',
      fontSize: '16px',
      textColor: '#333',
      paddingY: '40px',
    },
    fields: [
      { name: 'content', label: 'Contenido', type: 'textarea', required: true },
      { name: 'textAlign', label: 'Alineación', type: 'select', options: ['left', 'center', 'right', 'justify'] },
      { name: 'fontSize', label: 'Tamaño de fuente (px)', type: 'number-unit', defaultUnit: 'px', units: ['px', 'rem', 'em'] },
      { name: 'textColor', label: 'Color de texto', type: 'color' },
      { name: 'textFont', label: 'Fuente', type: 'font', options: FONT_OPTIONS },
      { name: 'paddingY', label: 'Espaciado vertical (px)', type: 'number-unit', defaultUnit: 'px', units: ['px'] },
    ],
  },
  
  image: {
    id: 'image',
    label: 'Imagen',
    icon: 'Image',
    description: 'Imagen individual',
    defaultProps: {
      src: '',
      srcPos: '50% 50%',
      srcFilter: '',
      alt: 'Imagen',
      width: '100%',
      height: 'auto',
      objectFit: 'cover',
      borderRadius: '0px',
      paddingY: '20px',
    },
    fields: [
      { name: 'src', label: 'Imagen', type: 'image-editable', required: true },
      { name: 'alt', label: 'Texto alternativo', type: 'text' },
      { name: 'width', label: 'Ancho', type: 'number-unit', defaultUnit: '%', units: ['%', 'px'] },
      { name: 'height', label: 'Alto', type: 'number-unit', defaultUnit: 'px', units: ['px', 'auto'] },
      { name: 'objectFit', label: 'Ajuste', type: 'select', options: ['cover', 'contain', 'fill', 'none'] },
      { name: 'borderRadius', label: 'Borde redondeado (px)', type: 'number-unit', defaultUnit: 'px', units: ['px', '%'] },
      { name: 'paddingY', label: 'Espaciado vertical (px)', type: 'number-unit', defaultUnit: 'px', units: ['px'] },
    ],
  },
  
  countdown: {
    id: 'countdown',
    label: 'Cuenta Regresiva',
    icon: 'Clock',
    description: 'Contador hacia una fecha',
    defaultProps: {
      targetDate: new Date(Date.now() + 30 * 24 * 60 * 60 * 1000).toISOString().split('T')[0],
      title: 'Faltan',
      textColor: '#7c3aed',
      labelColor: '#888888',
      showDays: true,
      showHours: true,
      showMinutes: true,
      showSeconds: false,
      paddingY: '40px',
    },
    fields: [
      { name: 'targetDate', label: 'Fecha objetivo', type: 'date', required: true },
      { name: 'title', label: 'Título', type: 'text' },
      { name: 'textColor', label: 'Color números', type: 'color' },
      { name: 'labelColor', label: 'Color etiquetas (Días, Hrs…)', type: 'color' },
      { name: 'titleFont', label: 'Fuente del Título', type: 'font', options: FONT_OPTIONS },
      { name: 'textFont', label: 'Fuente del Texto', type: 'font', options: FONT_OPTIONS },
      { name: 'showDays', label: 'Mostrar días', type: 'checkbox' },
      { name: 'showHours', label: 'Mostrar horas', type: 'checkbox' },
      { name: 'showMinutes', label: 'Mostrar minutos', type: 'checkbox' },
      { name: 'showSeconds', label: 'Mostrar segundos', type: 'checkbox' },
      { name: 'paddingY', label: 'Espaciado vertical (px)', type: 'number-unit', defaultUnit: 'px', units: ['px'] },
    ],
  },
  
  gallery: {
    id: 'gallery',
    label: 'Galería',
    icon: 'Grid',
    description: 'Galería de imágenes',
    defaultProps: {
      images: [],
      layout: 'polaroid',
      title: 'Galeria',
      subtitle: 'Nuestros mejores recuerdos',
      columns: 3,
      gap: '10px',
      borderRadius: '8px',
      paddingY: '40px',
      textColor: '#333333'
    },
    fields: [
      { name: 'title', label: 'Título', type: 'text' },
      { name: 'subtitle', label: 'Subtítulo', type: 'text' },
      { name: 'layout', label: 'Estilo de Galería', type: 'select', options: ['polaroid', 'grid', 'masonry'] },
      { name: 'images', label: 'Imágenes', type: 'image-array' },
      { name: 'titleFont', label: 'Tipografía de Título', type: 'font', options: FONT_OPTIONS },
      { name: 'textFont', label: 'Tipografía de Textos', type: 'font', options: FONT_OPTIONS },
      { name: 'textColor', label: 'Color de los Textos', type: 'color' },
      { name: 'columns', label: 'Columnas', type: 'number', min: 1, max: 6 },
      { name: 'gap', label: 'Espacio entre imágenes (px)', type: 'number-unit', defaultUnit: 'px', units: ['px'] },
      { name: 'borderRadius', label: 'Borde redondeado (px)', type: 'number-unit', defaultUnit: 'px', units: ['px', '%'] },
      { name: 'paddingY', label: 'Espaciado vertical (px)', type: 'number-unit', defaultUnit: 'px', units: ['px'] },
    ],
  },
  
  map: {
    id: 'map',
    label: 'Mapa / Ubicación',
    icon: 'MapPin',
    description: 'Ubicación con Google Maps o Waze',
    defaultProps: {
      mapType: 'google_maps',
      address: '',
      embedUrl: '',
      height: '400px',
      title: 'Ubicación',
      textColor: '#1a1a1a',
      paddingY: '40px',
    },
    fields: [
      { name: 'mapType', label: 'Plataforma', type: 'select', options: ['google_maps', 'waze'], optionLabels: { google_maps: 'Google Maps', waze: 'Waze' } },
      { name: 'title', label: 'Título', type: 'text' },
      { name: 'address', label: 'Dirección', type: 'text' },
      { name: 'embedUrl', label: 'Pega el código iframe de Google Maps', type: 'textarea', placeholder: '<iframe src="https://www.google.com/maps/embed?pb=...">', showWhen: { field: 'mapType', value: 'google_maps' } },
      { name: 'embedUrl', label: 'Link de Waze', type: 'text', placeholder: 'https://waze.com/ul/...', showWhen: { field: 'mapType', value: 'waze' } },
      { name: 'height', label: 'Alto del mapa (px)', type: 'number-unit', defaultUnit: 'px', units: ['px'], showWhen: { field: 'mapType', value: 'google_maps' } },
      { name: 'textColor', label: 'Color de texto', type: 'color' },
      { name: 'paddingY', label: 'Espaciado vertical (px)', type: 'number-unit', defaultUnit: 'px', units: ['px'] },
    ],
  },
  
  rsvp: {
    id: 'rsvp',
    label: 'RSVP',
    icon: 'Check',
    description: 'Botón de confirmación de asistencia',
    defaultProps: {
      title: 'Confirma tu asistencia',
      subtitle: 'Nos encantaría que pudieras acompañarnos en este día especial.',
      buttonText: 'Confirmar Asistencia',
      buttonColor: '#7c3aed',
      buttonTextColor: '#fff',
      textColor: '#1a1a1a',
      accentColor: '#7c3aed',
      textAlign: 'center',
      enabled: true,
      paddingY: '60px',
      popupTitle: 'Confirma tu asistencia',
      popupSubtitle: 'Tu presencia hace el día especial',
      popupAccentColor: '#7c3aed',
      popupBgColor: '#ffffff',
      successTitle: '¡Gracias por confirmar!',
      successMessage: 'Tu respuesta ha sido registrada con éxito.',
      successConfirmedText: '¡Te esperamos con mucha ilusión!',
    },
    fields: [
      { name: 'enabled', label: 'Activado', type: 'checkbox' },
      { name: 'title', label: 'Título', type: 'text' },
      { name: 'subtitle', label: 'Subtítulo', type: 'textarea' },
      { name: 'textColor', label: 'Color de texto', type: 'color' },
      { name: 'buttonText', label: 'Texto del botón', type: 'text', required: true },
      { name: 'buttonColor', label: 'Color del botón', type: 'color' },
      { name: 'buttonTextColor', label: 'Color texto botón', type: 'color' },
      { name: 'accentColor', label: 'Color decorativo', type: 'color' },
      { name: 'textAlign', label: 'Alineación', type: 'select', options: ['left', 'center', 'right'] },
      { name: 'paddingY', label: 'Espaciado vertical (px)', type: 'number-unit', defaultUnit: 'px', units: ['px'] },
      { name: 'popupTitle', label: 'Popup: Título', type: 'text' },
      { name: 'popupSubtitle', label: 'Popup: Subtítulo', type: 'text' },
      { name: 'popupAccentColor', label: 'Popup: Color acento', type: 'color' },
      { name: 'popupBgColor', label: 'Popup: Color de fondo', type: 'color' },
      { name: 'successTitle', label: 'Éxito: Título', type: 'text' },
      { name: 'successMessage', label: 'Éxito: Mensaje', type: 'text' },
      { name: 'successConfirmedText', label: 'Éxito: Texto confirmado', type: 'text' },
    ],
  },
  
  music_player: {
    id: 'music_player',
    label: 'Reproductor de Música',
    icon: 'Music',
    description: 'Reproductor de audio o embed de plataforma',
    defaultProps: {
      playerType: 'custom',
      audioUrl: '',
      embedUrl: '',
      autoplay: false,
      loop: true,
      title: 'Nuestra canción',
      subtitle: '',
      coverImage: '',
      coverImagePos: '50% 50%',
      coverImageFilter: '',
      showControls: true,
      textColor: '#ffffff',
      titleFontSize: '18px',
      subtitleFontSize: '14px',
      paddingY: '30px',
      embedHeight: 352,
    },
    fields: [
      { name: 'playerType', label: 'Tipo de reproductor', type: 'select', options: ['custom', 'spotify', 'youtube_music', 'deezer', 'apple_music'], optionLabels: { custom: 'Custom', spotify: 'Spotify', youtube_music: 'YouTube Music', deezer: 'Deezer', apple_music: 'Apple Music' } },
      { name: 'title', label: 'Título', type: 'text' },
      { name: 'titleFontSize', label: 'Tamaño del título (px)', type: 'number-unit', defaultUnit: 'px', units: ['px'] },
      { name: 'subtitle', label: 'Subtítulo', type: 'text' },
      { name: 'subtitleFontSize', label: 'Tamaño del subtítulo (px)', type: 'number-unit', defaultUnit: 'px', units: ['px'] },
      { name: 'audioUrl', label: 'URL del audio (mp3, ogg...)', type: 'text', showWhen: { field: 'playerType', value: 'custom' } },
      { name: 'coverImage', label: 'Imagen de portada', type: 'image-editable', showWhen: { field: 'playerType', value: 'custom' } },
      { name: 'autoplay', label: 'Reproducción automática', type: 'checkbox', showWhen: { field: 'playerType', value: 'custom' } },
      { name: 'loop', label: 'Repetir', type: 'checkbox', showWhen: { field: 'playerType', value: 'custom' } },
      { name: 'embedUrl', label: 'Link de YouTube Music', type: 'text', placeholder: 'https://music.youtube.com/watch?v=...', showWhen: { field: 'playerType', value: 'youtube_music' } },
      { name: 'embedUrl', label: 'Pega el código iframe de Spotify', type: 'textarea', placeholder: '<iframe src="https://open.spotify.com/embed/...">', showWhen: { field: 'playerType', value: 'spotify' } },
      { name: 'embedUrl', label: 'Pega el código iframe de Deezer', type: 'textarea', placeholder: '<iframe title="deezer-widget" src="...">', showWhen: { field: 'playerType', value: 'deezer' } },
      { name: 'embedUrl', label: 'Pega el código iframe de Apple Music', type: 'textarea', placeholder: '<iframe src="https://embed.music.apple.com/...">', showWhen: { field: 'playerType', value: 'apple_music' } },
      { name: 'embedHeight', label: 'Altura del reproductor (px)', type: 'number', min: 80, max: 600 },
      { name: 'textColor', label: 'Color de texto', type: 'color' },
      { name: 'titleFont', label: 'Fuente del Título', type: 'font', options: FONT_OPTIONS },
      { name: 'textFont', label: 'Fuente del Texto', type: 'font', options: FONT_OPTIONS },
      { name: 'paddingY', label: 'Espaciado vertical (px)', type: 'number-unit', defaultUnit: 'px', units: ['px'] },
    ],
  },
  
  divider: {
    id: 'divider',
    label: 'Separador',
    icon: 'Minus',
    description: 'Línea divisoria decorativa',
    defaultProps: {
      color: '#e5e7eb',
      thickness: '1px',
      width: '100%',
      style: 'solid',
      paddingY: '20px',
    },
    fields: [
      { name: 'color', label: 'Color', type: 'color' },
      { name: 'thickness', label: 'Grosor', type: 'number-unit', defaultUnit: 'px', units: ['px'] },
      { name: 'width', label: 'Ancho', type: 'number-unit', defaultUnit: '%', units: ['%', 'px'] },
      { name: 'style', label: 'Estilo', type: 'divider-select', options: [
        {label: 'Sólida', value: 'solid'},
        {label: 'Rayada', value: 'dashed'},
        {label: 'Punteada', value: 'dotted'},
        {label: 'Doble Línea', value: 'double'},
        {label: 'Diseño Botánico 1', value: 'div-1'},
        {label: 'Diseño Botánico 2', value: 'div-2'},
        {label: 'Ondas Cruzadas', value: 'div-3'},
        {label: 'Hoja Larga', value: 'div-4'},
        {label: 'Ondas Elegantes', value: 'div-5'},
        {label: 'Rombos y Hojas', value: 'div-6'},
        {label: 'Rombo Minimalista', value: 'div-7'},
        {label: 'Volutas 1', value: 'div-8'},
        {label: 'Volutas 2', value: 'div-9'},
        {label: 'Ondas Cortas', value: 'div-10'},
        {label: 'Rombos Punteados', value: 'div-11'},
        {label: 'Ondas Botánicas', value: 'div-12'},
        {label: 'Flecha Diamante', value: 'div-13'},
        {label: 'Rombos Lineales', value: 'div-14'}
      ] },
      { name: 'paddingY', label: 'Espaciado vertical (px)', type: 'number-unit', defaultUnit: 'px', units: ['px'] },
    ],
  },

  video: {
    id: 'video',
    label: 'Video',
    icon: 'Video',
    description: 'Video de YouTube, Vimeo o archivo',
    defaultProps: {
      title: '',
      subtitle: '',
      videoUrl: '',
      aspectRatio: '16/9',
      autoplay: false,
      muted: true,
      loop: false,
      paddingY: '40px',
    },
    fields: [
      { name: 'title', label: 'Título', type: 'text' },
      { name: 'subtitle', label: 'Subtítulo', type: 'text' },
      { name: 'videoUrl', label: 'URL del video (YouTube, Vimeo o MP4)', type: 'text', required: true },
      { name: 'aspectRatio', label: 'Aspecto', type: 'select', options: ['16/9', '4/3', '1/1'] },
      { name: 'autoplay', label: 'Reproducción automática', type: 'checkbox' },
      { name: 'muted', label: 'Silenciado al inicio', type: 'checkbox' },
      { name: 'loop', label: 'Repetir', type: 'checkbox' },
      { name: 'paddingY', label: 'Espaciado vertical (px)', type: 'number-unit', defaultUnit: 'px', units: ['px'] },
    ],
  },

  couple: {
    id: 'couple',
    label: 'Los Novios',
    icon: 'Heart',
    description: 'Presentación de la pareja',
    defaultProps: {
      title: 'Los novios',
      subtitle: 'Nuestra historia de amor',
      person1Name: 'Ana García',
      person1Photo: '',
      person1PhotoPos: '50% 20%',
      person1PhotoFilter: '',
      person1Description: 'Amante de los viajes y el café. Soñadora por naturaleza.',
      person2Name: 'Carlos López',
      person2Photo: '',
      person2PhotoPos: '50% 20%',
      person2PhotoFilter: '',
      person2Description: 'Músico de corazón. Se enamoró de ella a primera vista.',
      decorationIcon: 'LuHeart',
      textColor: '#1a1a1a',
      paddingY: '60px',
    },
    fields: [
      { name: 'title', label: 'Título de la sección', type: 'text' },
      { name: 'subtitle', label: 'Subtítulo', type: 'text' },
      { name: 'decorationIcon', label: 'Icono central', type: 'icon' },
      { name: 'person1Name', label: 'Nombre persona 1', type: 'text' },
      { name: 'person1Photo', label: 'Foto persona 1', type: 'image-editable' },
      { name: 'person1Description', label: 'Descripción persona 1', type: 'textarea' },
      { name: 'person2Name', label: 'Nombre persona 2', type: 'text' },
      { name: 'person2Photo', label: 'Foto persona 2', type: 'image-editable' },
      { name: 'person2Description', label: 'Descripción persona 2', type: 'textarea' },
      { name: 'textColor', label: 'Color de texto', type: 'color' },
      { name: 'titleFont', label: 'Fuente del Título', type: 'font', options: FONT_OPTIONS },
      { name: 'textFont', label: 'Fuente del Texto', type: 'font', options: FONT_OPTIONS },
      { name: 'paddingY', label: 'Espaciado vertical (px)', type: 'number-unit', defaultUnit: 'px', units: ['px'] },
    ],
  },

  schedule: {
    id: 'schedule',
    label: 'Itinerario',
    icon: 'CalendarDays',
    description: 'Programa del evento en línea de tiempo',
    defaultProps: {
      title: 'Programa del día',
      subtitle: 'Un día que nunca olvidaremos',
      events: [
        { time: '14:00', icon: 'LuChurch', title: 'Ceremonia', location: 'Iglesia San José', description: 'Ceremonia religiosa de matrimonio' },
        { time: '16:00', icon: 'LuCamera', title: 'Sesión de fotos', location: 'Jardín del evento', description: '' },
        { time: '18:00', icon: 'LuWine', title: 'Cóctel de bienvenida', location: 'Salón principal', description: 'Bebidas y aperitivos' },
        { time: '20:00', icon: 'LuUtensilsCrossed', title: 'Cena y baile', location: 'Salón principal', description: '¡A bailar toda la noche!' },
      ],
      textColor: '#1a1a1a',
      accentColor: '#7c3aed',
      paddingY: '60px',
    },
    fields: [
      { name: 'title', label: 'Título', type: 'text' },
      { name: 'subtitle', label: 'Subtítulo', type: 'text' },
      { name: 'accentColor', label: 'Color de acento', type: 'color' },
      { name: 'textColor', label: 'Color de texto', type: 'color' },
      { name: 'events', label: 'Eventos del itinerario', type: 'array-editor', itemShape: { time: 'text', icon: 'icon', title: 'text', location: 'text', description: 'text' } },
      { name: 'titleFont', label: 'Fuente del Título', type: 'font', options: FONT_OPTIONS },
      { name: 'textFont', label: 'Fuente del Texto', type: 'font', options: FONT_OPTIONS },
      { name: 'paddingY', label: 'Espaciado vertical (px)', type: 'number-unit', defaultUnit: 'px', units: ['px'] },
    ],
  },

  dress_code: {
    id: 'dress_code',
    label: 'Código de Vestimenta',
    icon: 'Shirt',
    description: 'Indicaciones de vestimenta y colores',
    defaultProps: {
      title: 'Código de vestimenta',
      subtitle: 'Queremos que estés cómodo/a y elegante',
      attire: 'Formal',
      attireIcon: '',
      colors: ['#E8D5B7', '#C9B8A8', '#8B7355', '#FFFFFF'],
      note: 'Por favor evitar el color blanco, reservado para la novia.',
      textColor: '#1a1a1a',
      paddingY: '60px',
    },
    fields: [
      { name: 'title', label: 'Título', type: 'text' },
      { name: 'subtitle', label: 'Subtítulo', type: 'text' },
      { name: 'attire', label: 'Tipo de vestimenta', type: 'select', options: ['Formal', 'Semi-formal', 'Casual elegante', 'Casual', 'Cocktail', 'Black Tie', 'Playa', 'Fantasía'] },
      { name: 'attireIcon', label: 'Icono de vestimenta', type: 'icon-or-image' },
      { name: 'note', label: 'Nota adicional', type: 'textarea' },
      { name: 'colors', label: 'Paleta de colores sugeridos', type: 'color-array' },
      { name: 'textColor', label: 'Color de texto', type: 'color' },
      { name: 'titleFont', label: 'Fuente del Título', type: 'font', options: FONT_OPTIONS },
      { name: 'textFont', label: 'Fuente del Texto', type: 'font', options: FONT_OPTIONS },
      { name: 'paddingY', label: 'Espaciado vertical (px)', type: 'number-unit', defaultUnit: 'px', units: ['px'] },
    ],
  },

  gifts: {
    id: 'gifts',
    label: 'Mesa de Regalos',
    icon: 'Gift',
    description: 'Lista de regalos y cuentas bancarias',
    defaultProps: {
      title: 'Mesa de regalos',
      subtitle: 'Tu presencia es el mejor regalo',
      message: 'Si deseas obsequiarnos algo, con mucho amor te compartimos estos detalles.',
      banks: [
        { bank: 'Banco Industrial', name: 'Ana García', account: '001-234567-8', type: 'Cuenta de ahorro' },
      ],
      wishlistUrl: '',
      textColor: '#1a1a1a',
      accentColor: '#7c3aed',
      paddingY: '60px',
    },
    fields: [
      { name: 'title', label: 'Título', type: 'text' },
      { name: 'subtitle', label: 'Subtítulo', type: 'text' },
      { name: 'message', label: 'Mensaje', type: 'textarea' },
      { name: 'wishlistUrl', label: 'Link a lista externa (Amazon, etc.)', type: 'text' },
      { name: 'accentColor', label: 'Color de acento', type: 'color' },
      { name: 'textColor', label: 'Color de texto', type: 'color' },
      { name: 'banks', label: 'Cuentas bancarias', type: 'array-editor', itemShape: { bank: 'text', name: 'text', account: 'text', type: 'text' } },
      { name: 'titleFont', label: 'Fuente del Título', type: 'font', options: FONT_OPTIONS },
      { name: 'textFont', label: 'Fuente del Texto', type: 'font', options: FONT_OPTIONS },
      { name: 'paddingY', label: 'Espaciado vertical (px)', type: 'number-unit', defaultUnit: 'px', units: ['px'] },
    ],
  },

  quote: {
    id: 'quote',
    label: 'Cita / Poema',
    icon: 'Quote',
    description: 'Frase, poema o cita especial',
    defaultProps: {
      text: '«En cada amor hay una nueva vida que comienza, una historia que vale la pena contar.»',
      author: '',
      fontSize: '24px',
      textColor: '#ffffff',
      accentColor: '#f9a8d4',
      paddingY: '80px',
    },
    fields: [
      { name: 'text', label: 'Texto de la cita', type: 'textarea', required: true },
      { name: 'author', label: 'Autor / Fuente', type: 'text' },
      { name: 'fontSize', label: 'Tamaño de fuente', type: 'select', options: ['18px', '22px', '24px', '28px', '32px', '36px'] },
      { name: 'textColor', label: 'Color de texto', type: 'color' },
      { name: 'titleFont', label: 'Fuente del Título', type: 'font', options: FONT_OPTIONS },
      { name: 'textFont', label: 'Fuente del Texto', type: 'font', options: FONT_OPTIONS },
      { name: 'accentColor', label: 'Color de acento', type: 'color' },
      { name: 'paddingY', label: 'Espaciado vertical (px)', type: 'number-unit', defaultUnit: 'px', units: ['px'] },
    ],
  },

  hospedaje: {
    id: 'hospedaje',
    label: 'Hospedaje',
    icon: 'Hotel',
    description: 'Opciones de hospedaje cercanas',
    defaultProps: {
      title: 'Opciones de hospedaje',
      subtitle: 'Te recomendamos estas opciones cerca del lugar del evento',
      hotels: [
        { name: 'Hotel Gran Plaza', address: 'Av. Central 123', price: 'desde $800/noche', distance: '2km', stars: 4, note: 'Tarifa especial para invitados, menciona el evento', bookingUrl: '' },
      ],
      textColor: '#1a1a2e',
      accentColor: '#7c3aed',
      paddingY: '60px',
    },
    fields: [
      { name: 'title', label: 'Título', type: 'text' },
      { name: 'subtitle', label: 'Subtítulo', type: 'textarea' },
      { name: 'accentColor', label: 'Color de acento', type: 'color' },
      { name: 'textColor', label: 'Color de texto', type: 'color' },
      { name: 'hotels', label: 'Hoteles', type: 'array-editor', itemShape: { name: 'text', address: 'text', price: 'text', distance: 'text', stars: 'number', note: 'text', bookingUrl: 'text' } },
      { name: 'titleFont', label: 'Fuente del Título', type: 'font', options: FONT_OPTIONS },
      { name: 'textFont', label: 'Fuente del Texto', type: 'font', options: FONT_OPTIONS },
      { name: 'paddingY', label: 'Espaciado vertical (px)', type: 'number-unit', defaultUnit: 'px', units: ['px'] },
    ],
  },

  menu_event: {
    id: 'menu_event',
    label: 'Menú del Evento',
    icon: 'UtensilsCrossed',
    description: 'Menú de comida y bebidas',
    defaultProps: {
      title: 'Menú',
      subtitle: 'Una cena preparada especialmente para ti',
      categories: [
        {
          name: 'Entrada',
          icon: 'LuSalad',
          items: [
            { name: 'Ensalada Caprese', description: 'Tomate, mozzarella fresca y albahaca', tags: 'Vegetariano' },
            { name: 'Crema de champiñones', description: 'Con trufa negra y crutones artesanales', tags: '' },
          ],
        },
        {
          name: 'Plato Fuerte',
          icon: 'LuBeef',
          items: [
            { name: 'Filete de res', description: 'Con salsa de vino tinto y verduras al vapor', tags: '' },
            { name: 'Salmón en papillote', description: 'Con mantequilla de hierbas y arroz basmati', tags: 'Pescado' },
          ],
        },
        {
          name: 'Postre',
          icon: 'LuCakeSlice',
          items: [
            { name: 'Pastel de bodas', description: 'Vainilla y frutos rojos', tags: '' },
          ],
        },
      ],
      footer: 'Informamos de alergias alimentarias al momento de confirmar asistencia',
      textColor: '#1a1a2e',
      accentColor: '#D4AF37',
      paddingY: '60px',
    },
    fields: [
      { name: 'title', label: 'Título', type: 'text' },
      { name: 'subtitle', label: 'Subtítulo', type: 'text' },
      { name: 'footer', label: 'Nota al pie', type: 'textarea' },
      { name: 'accentColor', label: 'Color de acento', type: 'color' },
      { name: 'textColor', label: 'Color de texto', type: 'color' },
      { name: 'categories', label: 'Categorías del menú', type: 'array-editor', itemShape: { name: 'text', icon: 'icon' } },
      { name: 'titleFont', label: 'Fuente del Título', type: 'font', options: FONT_OPTIONS },
      { name: 'textFont', label: 'Fuente del Texto', type: 'font', options: FONT_OPTIONS },
      { name: 'paddingY', label: 'Espaciado vertical (px)', type: 'number-unit', defaultUnit: 'px', units: ['px'] },
    ],
  },
  photo_upload: {
    id: 'photo_upload',
    label: 'Fotos del Evento',
    icon: 'Camera',
    description: 'Los invitados suben sus fotos del evento',
    defaultProps: {
      title: '📸 Comparte tus fotos',
      subtitle: '¡No queremos perder ningún momento! Sube las fotos que tomaste en el evento.',
      buttonText: 'Subir mis fotos',
      buttonColor: '#7c3aed',
      accentColor: '#7c3aed',
      textColor: '#1a1a2e',
      maxPhotos: 100,
      columns: 3,
      paddingY: '60px',
    },
    fields: [
      { name: 'title', label: 'Título', type: 'text' },
      { name: 'subtitle', label: 'Subtítulo', type: 'textarea' },
      { name: 'buttonText', label: 'Texto del botón', type: 'text' },
      { name: 'accentColor', label: 'Color de acento', type: 'color' },
      { name: 'textColor', label: 'Color de texto', type: 'color' },
      { name: 'maxPhotos', label: 'Máximo de fotos', type: 'number', min: 1, max: 500 },
      { name: 'columns', label: 'Columnas de la galería', type: 'number', min: 2, max: 5 },
      { name: 'titleFont', label: 'Fuente del Título', type: 'font', options: FONT_OPTIONS },
      { name: 'textFont', label: 'Fuente del Texto', type: 'font', options: FONT_OPTIONS },
      { name: 'paddingY', label: 'Espaciado vertical (px)', type: 'number-unit', defaultUnit: 'px', units: ['px'] },
    ],
  },

  mask: {
    id: 'mask',
    label: 'Máscara',
    icon: 'Scissors',
    description: 'Texto o imagen recortada en una forma',
    defaultProps: {
      mode: 'image',
      shape: 'circle',
      image: '',
      text: 'Texto',
      textColor: '#ffffff',
      fontSize: '32px',
      fontWeight: '700',
      bgColor: '#ec4899',
      width: '280px',
      height: '280px',
      textAlign: 'center',
      paddingY: '40px',
    },
    fields: [
      { name: 'mode', label: 'Contenido', type: 'select', options: ['image', 'text'] },
      { name: 'shape', label: 'Forma', type: 'select', options: ['circle', 'ellipse', 'diamond', 'triangle', 'hexagon', 'pentagon', 'star', 'arrow_up', 'cross'] },
      { name: 'image', label: 'Imagen', type: 'image' },
      { name: 'bgColor', label: 'Color de fondo', type: 'color' },
      { name: 'text', label: 'Texto', type: 'text' },
      { name: 'textColor', label: 'Color de texto', type: 'color' },
      { name: 'fontSize', label: 'Tamaño de fuente (px)', type: 'number-unit', defaultUnit: 'px', units: ['px'] },
      { name: 'fontWeight', label: 'Grosor', type: 'select', options: ['400', '600', '700', '800', '900'] },
      { name: 'textAlign', label: 'Alineación texto', type: 'select', options: ['left', 'center', 'right'] },
      { name: 'width', label: 'Ancho (px)', type: 'number-unit', defaultUnit: 'px', units: ['px', '%'] },
      { name: 'height', label: 'Alto (px)', type: 'number-unit', defaultUnit: 'px', units: ['px'] },
      { name: 'paddingY', label: 'Espaciado vertical', type: 'number-unit', defaultUnit: 'px', units: ['px'] },
    ],
  },
};

export const getSectionConfig  = (type) => {
  const cfg = SECTION_TYPES[type];
  if (!cfg) return null;
  return { ...cfg, fields: [...(cfg.fields || []), ...BG_FIELDS] };
};
export const getDefaultProps   = (type) => ({ ...BG_DEFAULTS, ...(SECTION_TYPES[type]?.defaultProps || {}) });
export const getAllSectionTypes = () => Object.values(SECTION_TYPES);


